function objectAt(x,y){let best=null,bd=1e9;for(const o of [...state.objects,...state.plan.map(p=>({...p,planned:true}))]){const size=o.type==='hq'?3:1;const d=Math.max(Math.abs(x-(o.x+size/2)),Math.abs(y-(o.y+size/2)));if(d<bd&&d<Math.max(2.5,8/state.view.scale)){best=o;bd=d}}return best}
function structAt(x,y){for(let i=0;i<STRUCTS.length;i++){const s=STRUCTS[i],fz=fzone(s);if(x>=fz.x1&&x<=fz.x2&&y>=fz.y1&&y<=fz.y2)return i}return -1}
function anchors(includePlan=false){return state.objects.filter(o=>o.type==='hq'||o.type==='banner').concat(includePlan?state.plan:[])}
function connectedSet(includePlan=false){const a=anchors(includePlan),hq=a.filter(o=>o.type==='hq'),seen=new Set(hq.map(o=>o.id));const q=[...hq];while(q.length){const cur=q.shift(),cr=rectFor(cur);for(const o of a){if(seen.has(o.id))continue;if(overlapOrTouch(cr,rectFor(o))){seen.add(o.id);q.push(o)}}}return seen}
function targetCoveredByNetwork(si,includePlan=true){const s=STRUCTS[si],fz=fzone(s),seen=connectedSet(includePlan);for(const o of anchors(includePlan)){if(!seen.has(o.id))continue;if(overlap(rectFor(o),fz))return true}return false}
function territoryContainsCell(x,y,includePlan=true){const seen=connectedSet(includePlan);for(const o of anchors(includePlan)){if(!seen.has(o.id))continue;const r=rectFor(o);if(x>=r.x1&&x<r.x2&&y>=r.y1&&y<r.y2)return true}return false}
function coveredNodeCount(includePlan=true){if(!nodes.length)return 0;let c=0;const req=state.settings.resourcePct/100;for(const n of nodes){let k=0;for(let dy=0;dy<2;dy++)for(let dx=0;dx<2;dx++)if(territoryContainsCell(n.x+dx,n.y+dy,includePlan))k++;if(k/4>=req)c++}return c}
function nearbyNodeScore(x,y){if(!nodes.length||!state.settings.resourceAware)return 0;let c=0;const r=state.settings.bannerRadius+2;for(const n of nodes){if(Math.abs(n.x-x)<=r&&Math.abs(n.y-y)<=r)c++}return Math.min(12,c)}
function setTool(t){state.tool=t;document.querySelectorAll('.tool[data-tool]').forEach(b=>b.classList.toggle('on',b.dataset.tool===t));toast(t==='target'?'Tap an outpost/facility to toggle target':t==='banner'?'Tap to add existing TNT banners':t==='hq'?'Tap to place TNT HQ':'Move/select mode')}
function addObject(type,x,y){x=Math.round(x);y=Math.round(y);if(type==='hq'&&state.objects.filter(o=>o.type==='hq').length>=2){toast('Kingshot cap: 2 HQs');return}if(type==='banner'&&state.objects.filter(o=>o.type==='banner').length>=285){toast('Kingshot cap: 285 banners');return}const why=blockReason(type,x,y);if(why){toast('Blocked: '+why);return}pushHistory();const o={id:uid(),type,x,y,locked:type==='hq'};state.objects.push(o);state.plan=[];routeStats=null;state.selected=o.id;autosave();render();openSelection(o)}
function deleteObject(id){const i=state.objects.findIndex(o=>o.id===id);if(i<0)return;pushHistory();state.objects.splice(i,1);state.plan=[];state.selected=null;routeStats=null;closeSheet();autosave();render()}
function toggleTarget(i){if(!OUTPOST_CATS.has(STRUCTS[i][7])&&STRUCTS[i][7]!=='Sanctuary'&&STRUCTS[i][7]!=='Fortress'){toast('Choose an Outpost, Sanctuary, or Fortress');return}pushHistory();const p=state.targets.indexOf(i);if(p>=0)state.targets.splice(p,1);else state.targets.push(i);state.plan=[];routeStats=null;autosave();render();toast((p>=0?'Removed ':'Target: ')+STRUCTS[i][8])}
function openSelection(o){state.selected=o.id;const sheet=$('sheet'),b=$('sheetBody');const conn=connectedSet(true).has(o.id);b.innerHTML=`<h2>${o.type==='hq'?'🏰 TNT HQ':'🚩 TNT Banner'} ${o.planned?'<span class="blue">(planned)</span>':''}</h2><div class="sub">X:${o.x} Y:${o.y} · ${conn?'<span class="good">connected to HQ</span>':'<span class="bad">not connected to HQ</span>'}</div><div class="sheetgrid"><div class="card"><b>Territory</b><div class="big">${o.type==='hq'?3+2*state.settings.hqRadius:1+2*state.settings.bannerRadius}×${o.type==='hq'?3+2*state.settings.hqRadius:1+2*state.settings.bannerRadius}</div></div><div class="card"><b>Placement</b><div class="big ${blockReason(o.type,o.x,o.y)?'bad':'good'}">${blockReason(o.type,o.x,o.y)?'BLOCKED':'VALID'}</div></div></div>${o.planned?'':`<div class="actions"><button id="lockSel" class="secondary">${o.locked?'🔒 Locked':'🔓 Lock'}</button><button id="deleteSel" class="danger">Delete</button></div>`}`;sheet.classList.add('open');if(!o.planned){$('deleteSel').onclick=()=>deleteObject(o.id);$('lockSel').onclick=()=>{pushHistory();o.locked=!o.locked;autosave();openSelection(o);render()}}}
function closeSheet(){$('sheet').classList.remove('open')}
function openResult(){const b=$('sheetBody'),seen=connectedSet(true);const existing=state.objects.filter(o=>o.type==='banner').length,disc=state.objects.filter(o=>o.type==='banner'&&!seen.has(o.id)).length,covered=state.targets.filter(i=>targetCoveredByNetwork(i,true)).length;const before=nodes.length?coveredNodeCount(false):null,after=nodes.length?coveredNodeCount(true):null;b.innerHTML=`<h2>⚡ Optimised TNT route</h2><div class="sub">${state.targets.length?`${covered}/${state.targets.length} selected facilities reached`:'No targets selected'} · planned banners are blue. Existing connected banners remain green.</div><div class="sheetgrid"><div class="card"><b>New banners</b><div class="big blue">${state.plan.length}</div></div><div class="card"><b>Total banners</b><div class="big ${existing+state.plan.length>285?'bad':'good'}">${existing+state.plan.length}/285</div></div><div class="card"><b>Disconnected existing</b><div class="big ${disc?'bad':'good'}">${disc}</div></div><div class="card"><b>Resource nodes</b><div class="big">${before===null?'—':`${before} → ${after}`}</div></div></div><div class="actions"><button id="applyPlan" class="primary">Apply planned banners</button><button id="clearPlan" class="secondary">Clear preview</button></div><div class="sub" style="margin-top:9px">Optimizer minimizes added banner count first. “Resource-rich ties” only breaks equal/near-equal routes; it never intentionally adds extra banners just for a node.${terrain?'':' <span class="warn">Terrain/resource dataset is not loaded, so this preview is not mountain/lake validated.</span>'}</div>`;$('sheet').classList.add('open');$('clearPlan').onclick=()=>{pushHistory();state.plan=[];routeStats=null;autosave();closeSheet();render()};$('applyPlan').onclick=()=>{if(state.objects.filter(o=>o.type==='banner').length+state.plan.length>285){toast('Would exceed 285-banner cap');return}pushHistory();for(const p of state.plan)state.objects.push({...p,id:uid(),planned:false,type:'banner'});state.plan=[];routeStats=null;autosave();render();closeSheet();toast('Planned banners added to TNT layout')}}
function showCoordModal(){const b=$('modalBody');b.innerHTML=`<h2>Add by coordinate</h2><div class="sub">Use the exact X:Y shown in Kingshot.</div><div class="row" style="margin-top:12px"><div class="field"><label>Type</label><select id="coordType"><option value="banner">Banner</option><option value="hq">HQ</option><option value="target">Nearest facility as target</option></select></div><div class="field"><label>X</label><input id="coordX" inputmode="numeric" type="number" min="0" max="1199" value="${Math.round(state.view.cx)}"></div><div class="field"><label>Y</label><input id="coordY" inputmode="numeric" type="number" min="0" max="1199" value="${Math.round(state.view.cy)}"></div></div><button id="coordAdd" class="primary" style="width:100%;margin-top:12px">Add / set target</button>`;openModal();$('coordAdd').onclick=()=>{const t=$('coordType').value,x=+$('coordX').value,y=+$('coordY').value;if(t==='target'){let bi=-1,bd=1e9;STRUCTS.forEach((s,i)=>{if(!OUTPOST_CATS.has(s[7])&&s[7]!=='Sanctuary'&&s[7]!=='Fortress')return;const d=Math.hypot(s[0]-x,s[1]-y);if(d<bd){bd=d;bi=i}});if(bi>=0)toggleTarget(bi)}else addObject(t,x,y);closeModal()}}
function showFacilities(){const b=$('modalBody');const chosen=new Set(state.targets);b.innerHTML=`<h2>Facilities</h2><div class="sub">Tap Target to add/remove. Jump centers the map.</div><div class="field" style="margin-top:10px"><input id="facSearch" placeholder="Search Forager, Scholar, Sanctuary…"></div><div id="facList" class="facility-list"></div>`;openModal();const draw=()=>{const q=$('facSearch').value.trim().toLowerCase();$('facList').innerHTML=STRUCTS.map((s,i)=>({s,i})).filter(({s})=>(OUTPOST_CATS.has(s[7])||s[7]==='Sanctuary'||s[7]==='Fortress')&&(!q||(s[8]+' '+s[7]).toLowerCase().includes(q))).map(({s,i})=>`<div class="facility"><div><div class="fn">${chosen.has(i)?'🎯 ':''}${s[8]}</div><div class="fc">X:${s[0]} Y:${s[1]} · ${s[7]}</div></div><div class="row"><button data-j="${i}">Jump</button><button data-t="${i}">${chosen.has(i)?'Remove':'Target'}</button></div></div>`).join('');document.querySelectorAll('[data-j]').forEach(x=>x.onclick=()=>{const s=STRUCTS[+x.dataset.j];state.view.cx=s[0]+s[2]/2;state.view.cy=s[1]+s[2]/2;state.view.scale=5;render();closeModal()});document.querySelectorAll('[data-t]').forEach(x=>x.onclick=()=>{toggleTarget(+x.dataset.t);chosen.clear();state.targets.forEach(i=>chosen.add(i));draw()})};$('facSearch').oninput=draw;draw()}
function openModal(){$('modalWrap').classList.add('open')}function closeModal(){$('modalWrap').classList.remove('open')}
