class Heap{constructor(){this.a=[]}push(n){let a=this.a;a.push(n);let i=a.length-1;while(i){let p=(i-1)>>1;if(a[p].f<=n.f)break;a[i]=a[p];i=p}a[i]=n}pop(){const a=this.a;if(!a.length)return null;const r=a[0],x=a.pop();if(a.length){let i=0;while(true){let l=i*2+1,rn=l+1;if(l>=a.length)break;let c=rn<a.length&&a[rn].f<a[l].f?rn:l;if(a[c].f>=x.f)break;a[i]=a[c];i=c}a[i]=x}return r}get length(){return this.a.length}}
function key(x,y){return x+','+y}
function chebToRect(x,y,r){const dx=x<r.x1?r.x1-x:x>r.x2?r.x2-x:0,dy=y<r.y1?r.y1-y:y>r.y2?y-r.y2:0;return Math.max(dx,dy)}
function goalReached(x,y,targetRect){const br={x1:x-state.settings.bannerRadius,y1:y-state.settings.bannerRadius,x2:x+1+state.settings.bannerRadius,y2:y+1+state.settings.bannerRadius};return overlap(br,targetRect)}
function findRoute(network,targetIndex){const targetRect=fzone(STRUCTS[targetIndex]),reach=state.settings.linkReach;const starters=[];for(const o of network){const r=rectFor(o);const cx=(r.x1+r.x2)/2,cy=(r.y1+r.y2)/2;starters.push({x:Math.round(cx),y:Math.round(cy),anchor:o})}
for(const o of network)if(overlap(rectFor(o),targetRect))return[];
const heap=new Heap(),g=new Map(),parent=new Map(),origin=new Map();
const seedSet=new Set();for(const st of starters){const o=st.anchor,or=rectFor(o);const centerX=o.x+(o.type==='hq'?1:0),centerY=o.y+(o.type==='hq'?1:0);for(let dy=-reach;dy<=reach;dy++)for(let dx=-reach;dx<=reach;dx++){if(Math.max(Math.abs(dx),Math.abs(dy))!==reach)continue;const x=Math.round(centerX+dx),y=Math.round(centerY+dy);if(blockReason('banner',x,y))continue;const br=rectFor({type:'banner',x,y});if(!overlapOrTouch(or,br))continue;const k=key(x,y);if(seedSet.has(k))continue;seedSet.add(k);const h=Math.ceil(chebToRect(x,y,targetRect)/reach);const tie=state.settings.resourceAware?nearbyNodeScore(x,y)*.001:0;g.set(k,1);parent.set(k,null);origin.set(k,o);heap.push({x,y,g:1,f:1+h-tie})}}
let expanded=0,best=null;const maxExpand=50000;while(heap.length&&expanded++<maxExpand){const cur=heap.pop(),ck=key(cur.x,cur.y);if(cur.g!==g.get(ck))continue;if(goalReached(cur.x,cur.y,targetRect)){best=cur;break}const dxGoal=((targetRect.x1+targetRect.x2)/2)-cur.x,dyGoal=((targetRect.y1+targetRect.y2)/2)-cur.y;const sx=Math.sign(dxGoal),sy=Math.sign(dyGoal);
const moves=[];for(let d=-reach;d<=reach;d++){moves.push([d,-reach],[d,reach],[-reach,d],[reach,d])}moves.push([sx*Math.min(reach,Math.abs(Math.round(dxGoal))),sy*Math.min(reach,Math.abs(Math.round(dyGoal)))]);
const used=new Set();for(const [dx,dy] of moves){if(!dx&&!dy)continue;const mk=dx+','+dy;if(used.has(mk))continue;used.add(mk);const x=cur.x+dx,y=cur.y+dy;if(blockReason('banner',x,y))continue;const nk=key(x,y),ng=cur.g+1;if(ng>80)continue;const old=g.get(nk);if(old!==undefined&&old<=ng)continue;g.set(nk,ng);parent.set(nk,ck);const h=Math.ceil(chebToRect(x,y,targetRect)/reach),tie=state.settings.resourceAware?nearbyNodeScore(x,y)*.001:0;heap.push({x,y,g:ng,f:ng+h-tie})}}
if(!best)return null;const arr=[];let k=key(best.x,best.y);while(k){const [x,y]=k.split(',').map(Number);arr.push({id:'p'+uid(),type:'banner',x,y,planned:true});k=parent.get(k)}arr.reverse();return arr}
