function optimize(){closeSheet();if(!terrain)toast('Terrain dataset not loaded yet — route will ignore mountains/lakes');if(!state.objects.some(o=>o.type==='hq')){toast('Place at least one TNT HQ first');return}if(!state.targets.length){toast('Select at least one facility target');setTool('target');return}const conn=connectedSet(false);let network=state.objects.filter(o=>(o.type==='hq'||o.type==='banner')&&(o.type==='hq'||(!state.settings.useExisting?false:conn.has(o.id))));if(!network.length)network=state.objects.filter(o=>o.type==='hq');let remaining=[...state.targets],plan=[];let fail=[];
while(remaining.length){let best=null,bestI=-1;for(const ti of remaining){const r=findRoute(network.concat(plan),ti);if(r===null)continue;const score=r.length-(state.settings.resourceAware?r.reduce((s,p)=>s+nearbyNodeScore(p.x,p.y),0)*.0001:0);if(!best||score<best.score){best={r,score,ti};bestI=ti}}if(!best){fail.push(...remaining);break}plan.push(...best.r);network=network.concat(best.r);remaining=remaining.filter(x=>x!==bestI)}
const seen=new Set();plan=plan.filter(p=>{const k=key(p.x,p.y);if(seen.has(k)||state.objects.some(o=>o.type==='banner'&&o.x===p.x&&o.y===p.y))return false;seen.add(k);return true});state.plan=plan;routeStats={fail};autosave();render();if(fail.length)toast(`Could not route to ${fail.length} target(s) with current map rules`);openResult()}
function fitPlan(){const pts=state.objects.concat(state.plan).map(o=>[o.x,o.y]);state.targets.forEach(i=>pts.push([STRUCTS[i][0],STRUCTS[i][1]]));if(!pts.length){state.view={cx:600,cy:600,scale:.75};render();return}let x1=Infinity,y1=Infinity,x2=-Infinity,y2=-Infinity;pts.forEach(([x,y])=>{x1=Math.min(x1,x);x2=Math.max(x2,x);y1=Math.min(y1,y);y2=Math.max(y2,y)});state.view.cx=(x1+x2)/2;state.view.cy=(y1+y2)/2;state.view.scale=clamp(Math.min(W/(x2-x1+60),H/(y2-y1+140)),.35,12);render()}
function bulkImport(){const lines=$('bulkText').value.split(/\n+/),items=[];for(const line of lines){const m=line.trim().match(/^(HQ|B|T)\s*[,;:]?\s*(\d+)\s*[,;:]?\s*(\d+)$/i);if(!m)continue;items.push([m[1].toUpperCase(),+m[2],+m[3]])}if(!items.length){toast('No valid lines found');return}pushHistory();for(const [t,x,y] of items){if(t==='T'){let bi=-1,bd=1e9;STRUCTS.forEach((s,i)=>{const d=Math.hypot(s[0]-x,s[1]-y);if((OUTPOST_CATS.has(s[7])||s[7]==='Sanctuary'||s[7]==='Fortress')&&d<bd){bd=d;bi=i}});if(bi>=0&&!state.targets.includes(bi))state.targets.push(bi)}else{const type=t==='HQ'?'hq':'banner';if(!blockReason(type,x,y))state.objects.push({id:uid(),type,x,y,locked:type==='hq'})}}state.plan=[];autosave();render();fitPlan();toast(`Imported ${items.length} entries`)}
function syncSettings(){for(const k of ['bannerRadius','hqRadius','linkReach','resourcePct'])$(k).value=state.settings[k];for(const k of ['resourceAware','useExisting','showPlanTerr','showStruct','showFZones','showNodes','showTerrain','showZones','showGrid'])$(k).checked=!!state.settings[k]}
function bindSettings(){for(const k of ['bannerRadius','hqRadius','linkReach','resourcePct'])$(k).onchange=()=>{pushHistory();state.settings[k]=+$(k).value;state.plan=[];routeStats=null;autosave();render()};for(const k of ['resourceAware','useExisting','showPlanTerr','showStruct','showFZones','showNodes','showTerrain','showZones','showGrid'])$(k).onchange=()=>{state.settings[k]=$(k).checked;autosave();render()}}
function exportJSON(){const blob=new Blob([JSON.stringify({app:'TNT Territory Optimizer',version:1,created:new Date().toISOString(),...JSON.parse(snapshot())},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='TNT-territory-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importJSON(file){const r=new FileReader();r.onload=()=>{try{pushHistory();restore(r.result);fitPlan();toast('Plan imported')}catch(e){toast('Invalid plan file')}};r.readAsText(file)}
function exportPNG(){render();const a=document.createElement('a');a.href=canvas.toDataURL('image/png');a.download='TNT-territory-plan.png';a.click()}
