function screenFromWorld(x,y){const s=state.view.scale,wx=(x-state.view.cx)*s,wy=((GRID-1-y)-(GRID-1-state.view.cy))*s;return{x:W/2+wx,y:H/2+wy}}
function worldFromScreen(px,py){const s=state.view.scale;return{x:state.view.cx+(px-W/2)/s,y:state.view.cy-(py-H/2)/s}}
function resize(){dpr=Math.min(2,window.devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=Math.round(W*dpr);canvas.height=Math.round(H*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);render()}
function drawWorldRect(r,fill,stroke,alpha=1){const a=screenFromWorld(r.x1,r.y1),b=screenFromWorld(r.x2,r.y2);const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);ctx.globalAlpha=alpha;if(fill){ctx.fillStyle=fill;ctx.fillRect(x,y,w,h)}if(stroke){ctx.strokeStyle=stroke;ctx.strokeRect(x,y,w,h)}ctx.globalAlpha=1}
function visibleBounds(){const a=worldFromScreen(0,H),b=worldFromScreen(W,0);return{x1:clamp(Math.floor(a.x)-2,0,1199),y1:clamp(Math.floor(a.y)-2,0,1199),x2:clamp(Math.ceil(b.x)+2,0,1199),y2:clamp(Math.ceil(b.y)+2,0,1199)}}
function render(){if(!W||!H)return;ctx.clearRect(0,0,W,H);ctx.fillStyle='#071018';ctx.fillRect(0,0,W,H);const vb=visibleBounds(),s=state.view.scale;
if(state.settings.showZones){drawWorldRect({x1:0,y1:0,x2:1200,y2:1200},'#0a191d',null,.9);drawWorldRect({x1:300,y1:300,x2:900,y2:900},'#102d27',null,.6);drawWorldRect({x1:450,y1:450,x2:750,y2:750},'#163622',null,.58);drawWorldRect({x1:552,y1:552,x2:648,y2:648},'#3b2b1b',null,.6);drawWorldRect({x1:586,y1:586,x2:614,y2:614},'#451a24',null,.75)}
if(state.settings.showGrid&&s>2){const step=s>8?1:s>4?5:10;ctx.strokeStyle='rgba(255,255,255,.055)';ctx.lineWidth=1;for(let x=Math.floor(vb.x1/step)*step;x<=vb.x2;x+=step){const a=screenFromWorld(x,vb.y1),b=screenFromWorld(x,vb.y2);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}for(let y=Math.floor(vb.y1/step)*step;y<=vb.y2;y+=step){const a=screenFromWorld(vb.x1,y),b=screenFromWorld(vb.x2,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}}
if(terrain&&(state.settings.showTerrain||state.settings.showNodes)&&s>.65){const px=Math.max(1,s);for(let gy=vb.y1;gy<=vb.y2;gy++){const iy=GRID-1-gy;for(let gx=vb.x1;gx<=vb.x2;gx++){const t=terrain[iy*GRID+gx];if(!t)continue;if((t<=2&&!state.settings.showTerrain)||(t>=3&&!state.settings.showNodes))continue;const p=screenFromWorld(gx,gy+1);ctx.fillStyle=t===1?'#59616b':t===2?'#245e91':t===3?'#ffb300':t===4?'#66bb6a':t===5?'#b0bec5':'#42a5f5';ctx.globalAlpha=t<=2?.55:.9;ctx.fillRect(p.x,p.y,px+1,px+1)}}ctx.globalAlpha=1}
if(state.settings.showStruct){for(let i=0;i<STRUCTS.length;i++){const q=STRUCTS[i],r={x1:q[0],y1:q[1],x2:q[0]+q[2],y2:q[1]+q[2]};if(state.settings.showFZones)drawWorldRect(fzone(q),'rgba(255,85,96,.035)','rgba(255,95,105,.24)',1);drawWorldRect(r,q[6],'rgba(0,0,0,.65)',1);const c=screenFromWorld(q[0]+q[2]/2,q[1]+q[2]/2);if(s>1.4){ctx.fillStyle='#fff';ctx.font=`800 ${clamp(s*q[2]*.42,8,14)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(q[5],c.x,c.y)}if(s>4){ctx.font='10px system-ui';ctx.fillStyle='#dce8f4';ctx.fillText(q[8],c.x,c.y+q[2]*s*.7+8)}if(state.targets.includes(i)){ctx.strokeStyle='#ffd166';ctx.lineWidth=3;ctx.beginPath();ctx.arc(c.x,c.y,Math.max(11,q[2]*s+7),0,Math.PI*2);ctx.stroke();ctx.fillStyle='#ffd166';ctx.font='18px system-ui';ctx.fillText('🎯',c.x,c.y-18)}}}
const conn=connectedSet(false);if(state.settings.showPlanTerr){for(const o of state.objects.filter(o=>o.type==='hq'||o.type==='banner')){const ok=o.type==='hq'||conn.has(o.id);drawWorldRect(rectFor(o),ok?'rgba(83,168,255,.12)':'rgba(255,102,117,.08)',ok?'rgba(83,168,255,.26)':'rgba(255,102,117,.3)',1)}for(const p of state.plan)drawWorldRect(rectFor(p),'rgba(54,224,207,.10)','rgba(54,224,207,.32)',1)}
for(const o of state.objects){const size=o.type==='hq'?3:1,c=screenFromWorld(o.x+size/2,o.y+size/2),ok=o.type==='hq'||conn.has(o.id);ctx.fillStyle=o.type==='hq'?'#be8cff':ok?'#58df83':'#ff6675';const R=o.type==='hq'?Math.max(7,1.8*s):Math.max(5,1.2*s);ctx.beginPath();ctx.arc(c.x,c.y,R,0,Math.PI*2);ctx.fill();ctx.strokeStyle=o.locked?'#ffd166':'#071018';ctx.lineWidth=o.locked?2.5:1.5;ctx.stroke();if(o.type==='hq'||s>5){ctx.fillStyle='#061019';ctx.font=`900 ${o.type==='hq'?10:8}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.type==='hq'?'HQ':'B',c.x,c.y)}}for(const p of state.plan){const c=screenFromWorld(p.x+.5,p.y+.5);ctx.fillStyle='#36e0cf';ctx.beginPath();ctx.arc(c.x,c.y,Math.max(5,1.2*s),0,Math.PI*2);ctx.fill();ctx.strokeStyle='#d7fff9';ctx.lineWidth=1.4;ctx.stroke()}
ctx.strokeStyle='rgba(255,255,255,.2)';ctx.lineWidth=1;const tl=screenFromWorld(0,1199),br=screenFromWorld(1200,-1);ctx.strokeRect(tl.x,tl.y,br.x-tl.x,br.y-tl.y);$('countMeta').textContent=`${state.objects.filter(o=>o.type==='banner').length}/285 · 🎯${state.targets.length}`;const center=worldFromScreen(W/2,H/2);$('coordHud').textContent=`X:${Math.round(center.x)} Y:${Math.round(center.y)} · ${Math.round(s*100)}%`;}
