// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ags-slabs/Ags10ArchivePristine.tsx": () => import("../components/mockups/ags-slabs/Ags10ArchivePristine.tsx"),
  "./components/mockups/ags-slabs/Ags6Played.tsx": () => import("../components/mockups/ags-slabs/Ags6Played.tsx"),
  "./components/mockups/ags-slabs/Ags7NearMint.tsx": () => import("../components/mockups/ags-slabs/Ags7NearMint.tsx"),
  "./components/mockups/ags-slabs/Ags8Mint.tsx": () => import("../components/mockups/ags-slabs/Ags8Mint.tsx"),
  "./components/mockups/ags-slabs/Ags95Pristine.tsx": () => import("../components/mockups/ags-slabs/Ags95Pristine.tsx"),
  "./components/mockups/ags-slabs/Ags9GemMint.tsx": () => import("../components/mockups/ags-slabs/Ags9GemMint.tsx")
};
